reset;
option solver cplex;
option reset_initial_guesses 1;
option cplex_options 'outlev=0';
option solver_msg 0;
model src/z2.mod;
data src/z2.dat;
data out/z2-samples.dat;

let rho := 0.000001;
let lambda_risk := 1000;
let lambda_profit := 0.001;
let a_profit := -500;

set in_a_risk := {100, 400, 740};

display in_a_risk;

for {a in in_a_risk} {
	let a_risk := a;
	solve >/dev/null;
	display profit, {s in Scenarios} abs(risk[s]);
}
